name = "docbuild"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"

[[require]]
name = "MathUniverse"
path = "../"

[[require]]
scope = "leanprover"
name  = "doc-gen4"
rev   = "main"
