[package]
name = "mdx-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tera = "1"                   # or handlebars = "5"
clap = { version = "4", features = ["derive"] }
